### ISSUE TITLE
Support for Rules

### ISSUE THREAD

**Issue by vromero** [mozilla-iot/roku-adapter#3]
Thank you for this, it works great for me.

I was wondering about how to use this as a target in a Rule, in the drop down there is no property shown.

**Comment by mrstegeman** [comment]
What would you like to be able to do with a rule?

Currently, the only exposed property is the current app, which doesn't make a lot of sense as a rule input. In the future, we should be able to perform actions with inputs, which would allow you to use the 3 exposed actions here.

You'll probably want to follow mozilla-iot/gateway#996

**Comment by vromero** [comment]
@mrstegeman thanks for the info.

I can see how without mozilla-iot/gateway#996 is key to enable this as the kind of actions I'd like to do are things like: 

- tune hdmi1 (and then in nvidia shield with another adapter open netflix)
- open netflix
- power on
- power off (although these last two I guess could be exposed).

I'll follow that issue.
